name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout from GitHub repository
        uses: actions/checkout@v4
      - name: Init environment with mise
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Install node modules
        run: npm ci
      - name: Build application
        shell: bash
        run: |
          function retry {
            local n=1
            local max=3
            local delay=5
            while true; do
              "$@" && break || {
                if [[ $n -lt $max ]]; then
                  ((n++))
                  echo "Command failed. Attempt $n/$max:"
                  sleep $delay;
                else
                  echo "The command has failed after $n attempts."
                  return 1
                fi
              }
            done
          }
          retry npm run build
        env:
          GATSBY_GOOGLE_MAPS_API_KEY: ${{ secrets.GATSBY_GOOGLE_MAPS_API_KEY }}
          GATSBY_GOOGLE_MAPS_MAP_ID: ${{ secrets.GATSBY_GOOGLE_MAPS_MAP_ID }}
          GATSBY_GTM_ID: ${{ secrets.GATSBY_GTM_ID }}
